### ISSUE TITLE
Default Installation Issues

### ISSUE THREAD

**Issue by ceej21** [Netflix/dispatch-docker#37]
Hello, all I am aiming to do at this point is get Dispatch - docker up and running with the default files pulled from GitHub (including the .env file) - I am not entirely sure what to do after running both 

pip install -r requirements.txt 
./install.sh 

any help or step by step would be greatly appreciated

**Comment by B3lak0r** [comment]
> Hello, all I am aiming to do at this point is get Dispatch - docker up and running with the default files pulled from GitHub (including the .env file) - I am not entirely sure what to do after running both
> 
> pip install -r requirements.txt
> ./install.sh
> 
> any help or step by step would be greatly appreciated

1.- Begin with adding all the related plugins info into your .env file (take a look at .env.example as guide and read the documentation).
2.- Add a host port share for the web and web scheduler containers in your docker-compose.yml (in order to have external access).
3.- run ./install.sh
4.- track any error logs (in case if have) among the repo issues records, they're very useful.

**Comment by kevgliss** [comment]
Thanks for responding @B3lak0r, @ceej21 please open a new issue with a more specific issue/question if possible.
