### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by mrthankyou** [Netflix/dispatch-docker#81]
**Is your feature request related to a problem? Please describe.**
I'm relatively new to Docker and this is my first project using this tool. I have had IMMENSE frustration with installing this app and getting it to run smoothly. From what I've seen so far, I've seen two general steps to follow for installation:

1. Git clone the repo
2. Run `./install.sh`

Although both of these steps have gotten me somewhere, I'm still having trouble in particular with setting up the database. For example, it's not clear if ./install.sh is something to run within a docker or not. When I run the install.sh script, it creates a database on my local machine, and not in docker. This is something that took me hours to actually grasp since I thought the install.sh would do all the work for me.

From there I've had to rig up a custom solution to install the database within the docker `dispatch_postgres_1` container. Even then I'm still experiencing issues with my custom solution. My custom solution is as follows:

1. Initialize the database in the `dispatch_web_1` container via `dispatch database init`.
2. Enter psql into the `dispatch_postgres_1` container and copy and paste the contents of the sample data dump file into the psql console.

Even with this custom solution, I'm still getting errors such as:

```
web_1        | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column tag.tag_type_id does not exist
web_1        | LINE 2: ...tag_source, tag.discoverable AS tag_discoverable, tag.tag_ty...
```

Also, there is documentation on the dispatch CLI tool. Does this tool coincide with the ./install.sh script? Why does it feel like there is overlap between both tools, especially when it comes to initializing the database.

I have no idea what's going on at this point and am likely going to give up.

**Describe the solution you'd like**
It would be nice if there was a basic set of point-by-point instructions on how to install this application. The instructions should be designed for docker beginners. 

**Describe alternatives you've considered**
Alternatively, seeing links to a docker tutorial that explains how to install an application like this would be nice. However, I think that may be difficult.

Another approach is to record a screen of a fresh installation. Something like this may likely be faster than writing out the documentation.

**Additional context**
I understand that some of this ticket can be coming from my lack of knowledge with docker, but at the same time I can't help but feel like this _should_ be a simple installation considering you're using Docker in the first place. 

Any help would be appreciated. Thank you.

**Comment by kevgliss** [comment]
@mrthankyou I'm sorry you have had such difficulty getting Dispatch up and running. 

Since most of your issues seem to stem from the docker itself. I've moved your issue to the `dispatch-docker` repo so we can address issues here.

Before I attempt to address your individual concerns, I do want to point out that the docker related configurations we provide are merely a _convenience_ and is in no way required to run Dispatch itself (we don't use docker on our internal deployment). At the end of the day, Dispatch is a simple webserver and a postgres database. If you are more familiar with other deployment options that might be an easier path forward. 

Now to address your individual questions/concerns:

It seems there is some confusion between the `./install.sh` , `docker-compose.yml` and the `dispatch cli`,

`./install.sh` 
Is a simple shell script that attempts to ensure that your local environment is ready to use Dispatch in it's dockerized form. It does things like ensuring we have a docker binary installed, cleaning up old images pulling and starting new images as necessary. This too is a _convenience_ script and is not required to run Dispatch via docker. 

`docker-compose.yml`
This file describes the relationships between containers, in our case the architecture is pretty simple: We have one container running a webserver, once container running a scheduler, and one container running postgres. 

You noted that you were not expecting for postgres to be running locally, in fact all of these containers are running locally and will expose their ports to the host machine as necessary. We've chosen to expose the postgres port to the host machine to make some operations easier. 

`dispatch` command
The `dispatch` is part of the Dispatch application itself and exposes several helpful functions for interacting with Dispatch and it's database. This command becomes available when the application itself and is not related to docker, except that our docker images use some `dispatch` commands to configure the application. 

Specific answers:
> It would be nice if there was a basic set of point-by-point instructions on how to install this application. The instructions should be designed for docker beginners.

While I agree it would be nice, I don't believe we are planning to invest in the resources to create such documentation, we don't intend to be another resource for learning how docker works as there are plenty of resources of that [here(](https://docs.docker.com/get-started/). That said if the community wishes to provide such documentation, I would happily merge it.

Again, sorry you had so many issues with the install, we're constantly trying to make it as easy as possible but do assume some base technical knowledge in or documentation.

**Comment by mrthankyou** [comment]
Thanks for the detailed response. Over the past few days I've become more used to working with Docker and Dispatch. I think my initial frustration has now waned. If possible I would like to contribute some documentation (even if it's small) to the installation guide. This would be some combination of my own experience and what you've posted in the reply.

Thanks again for posting a detailed response. Let me know how I can help others make using this product easier!

**Comment by kevgliss** [comment]
No worries, always happy to merge in install document improvements regardless of size. 

Our main documentation is based out of: https://github.com/Netflix/dispatch/tree/master/docs

**Comment by mrthankyou** [comment]
Cool! Give me a few days as I'm rather occupied at the moment and I'll string something together. I'll introduce a PR when I have something presentable.
